package com.zx.business.model;

import com.zx.business.vo.PageVO;

public class BusAgentCompany extends PageVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.poll_code
     *
     * @mbg.generated
     */
    private String pollCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.charge_person
     *
     * @mbg.generated
     */
    private String chargePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.extend1
     *
     * @mbg.generated
     */
    private String extend1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.extend2
     *
     * @mbg.generated
     */
    private String extend2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.extend3
     *
     * @mbg.generated
     */
    private String extend3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_agent_company.extend4
     *
     * @mbg.generated
     */
    private String extend4;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_agent_company
     *
     * @mbg.generated
     */
    public BusAgentCompany(Integer id, String name, String pollCode, String phone, String address, Integer state, String chargePerson, String extend1, String extend2, String extend3, String extend4) {
        this.id = id;
        this.name = name;
        this.pollCode = pollCode;
        this.phone = phone;
        this.address = address;
        this.state = state;
        this.chargePerson = chargePerson;
        this.extend1 = extend1;
        this.extend2 = extend2;
        this.extend3 = extend3;
        this.extend4 = extend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_agent_company
     *
     * @mbg.generated
     */
    public BusAgentCompany() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.id
     *
     * @return the value of bus_agent_company.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.id
     *
     * @param id the value for bus_agent_company.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.name
     *
     * @return the value of bus_agent_company.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.name
     *
     * @param name the value for bus_agent_company.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.poll_code
     *
     * @return the value of bus_agent_company.poll_code
     *
     * @mbg.generated
     */
    public String getPollCode() {
        return pollCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.poll_code
     *
     * @param pollCode the value for bus_agent_company.poll_code
     *
     * @mbg.generated
     */
    public void setPollCode(String pollCode) {
        this.pollCode = pollCode == null ? null : pollCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.phone
     *
     * @return the value of bus_agent_company.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.phone
     *
     * @param phone the value for bus_agent_company.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.address
     *
     * @return the value of bus_agent_company.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.address
     *
     * @param address the value for bus_agent_company.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.state
     *
     * @return the value of bus_agent_company.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.state
     *
     * @param state the value for bus_agent_company.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.charge_person
     *
     * @return the value of bus_agent_company.charge_person
     *
     * @mbg.generated
     */
    public String getChargePerson() {
        return chargePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.charge_person
     *
     * @param chargePerson the value for bus_agent_company.charge_person
     *
     * @mbg.generated
     */
    public void setChargePerson(String chargePerson) {
        this.chargePerson = chargePerson == null ? null : chargePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.extend1
     *
     * @return the value of bus_agent_company.extend1
     *
     * @mbg.generated
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.extend1
     *
     * @param extend1 the value for bus_agent_company.extend1
     *
     * @mbg.generated
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1 == null ? null : extend1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.extend2
     *
     * @return the value of bus_agent_company.extend2
     *
     * @mbg.generated
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.extend2
     *
     * @param extend2 the value for bus_agent_company.extend2
     *
     * @mbg.generated
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2 == null ? null : extend2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.extend3
     *
     * @return the value of bus_agent_company.extend3
     *
     * @mbg.generated
     */
    public String getExtend3() {
        return extend3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.extend3
     *
     * @param extend3 the value for bus_agent_company.extend3
     *
     * @mbg.generated
     */
    public void setExtend3(String extend3) {
        this.extend3 = extend3 == null ? null : extend3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_agent_company.extend4
     *
     * @return the value of bus_agent_company.extend4
     *
     * @mbg.generated
     */
    public String getExtend4() {
        return extend4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_agent_company.extend4
     *
     * @param extend4 the value for bus_agent_company.extend4
     *
     * @mbg.generated
     */
    public void setExtend4(String extend4) {
        this.extend4 = extend4 == null ? null : extend4.trim();
    }
}