package com.zx.business.model;

import java.util.Date;

public class BusAccountManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_account_manage.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_account_manage.phone_num
     *
     * @mbg.generated
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_account_manage.verify_code
     *
     * @mbg.generated
     */
    private String verifyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_account_manage.forget_count
     *
     * @mbg.generated
     */
    private Integer forgetCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_account_manage.last_time
     *
     * @mbg.generated
     */
    private Date lastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_account_manage.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_account_manage.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_account_manage
     *
     * @mbg.generated
     */
    public BusAccountManage(Integer id, String phoneNum, String verifyCode, Integer forgetCount, Date lastTime, Date createTime, Date updateTime) {
        this.id = id;
        this.phoneNum = phoneNum;
        this.verifyCode = verifyCode;
        this.forgetCount = forgetCount;
        this.lastTime = lastTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_account_manage
     *
     * @mbg.generated
     */
    public BusAccountManage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_account_manage.id
     *
     * @return the value of bus_account_manage.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_account_manage.id
     *
     * @param id the value for bus_account_manage.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_account_manage.phone_num
     *
     * @return the value of bus_account_manage.phone_num
     *
     * @mbg.generated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_account_manage.phone_num
     *
     * @param phoneNum the value for bus_account_manage.phone_num
     *
     * @mbg.generated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_account_manage.verify_code
     *
     * @return the value of bus_account_manage.verify_code
     *
     * @mbg.generated
     */
    public String getVerifyCode() {
        return verifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_account_manage.verify_code
     *
     * @param verifyCode the value for bus_account_manage.verify_code
     *
     * @mbg.generated
     */
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode == null ? null : verifyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_account_manage.forget_count
     *
     * @return the value of bus_account_manage.forget_count
     *
     * @mbg.generated
     */
    public Integer getForgetCount() {
        return forgetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_account_manage.forget_count
     *
     * @param forgetCount the value for bus_account_manage.forget_count
     *
     * @mbg.generated
     */
    public void setForgetCount(Integer forgetCount) {
        this.forgetCount = forgetCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_account_manage.last_time
     *
     * @return the value of bus_account_manage.last_time
     *
     * @mbg.generated
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_account_manage.last_time
     *
     * @param lastTime the value for bus_account_manage.last_time
     *
     * @mbg.generated
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_account_manage.create_time
     *
     * @return the value of bus_account_manage.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_account_manage.create_time
     *
     * @param createTime the value for bus_account_manage.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_account_manage.update_time
     *
     * @return the value of bus_account_manage.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_account_manage.update_time
     *
     * @param updateTime the value for bus_account_manage.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}