package com.zx.business.model;

public class BusCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.agent_id
     *
     * @mbg.generated
     */
    private Integer agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.phone_num
     *
     * @mbg.generated
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    public BusCustomer(Integer id, Integer agentId, String name, String phoneNum, Boolean sex) {
        this.id = id;
        this.agentId = agentId;
        this.name = name;
        this.phoneNum = phoneNum;
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    public BusCustomer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.id
     *
     * @return the value of bus_customer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.id
     *
     * @param id the value for bus_customer.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.agent_id
     *
     * @return the value of bus_customer.agent_id
     *
     * @mbg.generated
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.agent_id
     *
     * @param agentId the value for bus_customer.agent_id
     *
     * @mbg.generated
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.name
     *
     * @return the value of bus_customer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.name
     *
     * @param name the value for bus_customer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.phone_num
     *
     * @return the value of bus_customer.phone_num
     *
     * @mbg.generated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.phone_num
     *
     * @param phoneNum the value for bus_customer.phone_num
     *
     * @mbg.generated
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.sex
     *
     * @return the value of bus_customer.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_customer.sex
     *
     * @param sex the value for bus_customer.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }
}