package com.zx.business.model;

import java.util.Date;

public class BusCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.agent_id
     *
     * @mbg.generated
     */
    private Integer agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.phone_num
     *
     * @mbg.generated
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_customer.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    public BusCustomer(Integer agentId, String name, String phoneNum, Integer sex) {
        this.agentId = agentId;
        this.name = name;
        this.phoneNum = phoneNum;
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.id
     *
     * @return the value of bus_customer.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.agent_id
     *
     * @return the value of bus_customer.agent_id
     *
     * @mbg.generated
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.name
     *
     * @return the value of bus_customer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.phone_num
     *
     * @return the value of bus_customer.phone_num
     *
     * @mbg.generated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.sex
     *
     * @return the value of bus_customer.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.create_time
     *
     * @return the value of bus_customer.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_customer.update_time
     *
     * @return the value of bus_customer.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }
}