package com.zx.business.model;

import java.util.Date;

public class BusDeal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.real_estate_id
     *
     * @mbg.generated
     */
    private Integer realEstateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.real_estate_name
     *
     * @mbg.generated
     */
    private String realEstateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.customer_phone
     *
     * @mbg.generated
     */
    private String customerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.report_user_id
     *
     * @mbg.generated
     */
    private Integer reportUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.report_user_phone
     *
     * @mbg.generated
     */
    private String reportUserPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.report_company
     *
     * @mbg.generated
     */
    private String reportCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.appointment_time
     *
     * @mbg.generated
     */
    private Date appointmentTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.subscribe_time
     *
     * @mbg.generated
     */
    private Date subscribeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.manager_id
     *
     * @mbg.generated
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.manager_phone
     *
     * @mbg.generated
     */
    private String managerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.arrive_certify_photo_path
     *
     * @mbg.generated
     */
    private String arriveCertifyPhotoPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.subscribe_money
     *
     * @mbg.generated
     */
    private String subscribeMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.subscribe_commision
     *
     * @mbg.generated
     */
    private String subscribeCommision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.subscribe_photo_pahts
     *
     * @mbg.generated
     */
    private String subscribePhotoPahts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.appointment_operate_time
     *
     * @mbg.generated
     */
    private Date appointmentOperateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.report_operate_time
     *
     * @mbg.generated
     */
    private Date reportOperateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.arrive_operate_time
     *
     * @mbg.generated
     */
    private Date arriveOperateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.subscribe_operate_time
     *
     * @mbg.generated
     */
    private Date subscribeOperateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_deal.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    public BusDeal() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    public BusDeal(Integer id, Integer realEstateId, String realEstateName, Integer state, Integer customerId, String customerPhone, String customerName, Integer reportUserId, String reportUserPhone, String reportCompany, Date appointmentTime, Date subscribeTime, Integer managerId, String managerPhone, String arriveCertifyPhotoPath, String subscribeMoney, String subscribeCommision, String subscribePhotoPahts, Date appointmentOperateTime, Date reportOperateTime, Date arriveOperateTime, Date subscribeOperateTime, Date createTime, Date updateTime) {
        this.id = id;
        this.realEstateId = realEstateId;
        this.realEstateName = realEstateName;
        this.state = state;
        this.customerId = customerId;
        this.customerPhone = customerPhone;
        this.customerName = customerName;
        this.reportUserId = reportUserId;
        this.reportUserPhone = reportUserPhone;
        this.reportCompany = reportCompany;
        this.appointmentTime = appointmentTime;
        this.subscribeTime = subscribeTime;
        this.managerId = managerId;
        this.managerPhone = managerPhone;
        this.arriveCertifyPhotoPath = arriveCertifyPhotoPath;
        this.subscribeMoney = subscribeMoney;
        this.subscribeCommision = subscribeCommision;
        this.subscribePhotoPahts = subscribePhotoPahts;
        this.appointmentOperateTime = appointmentOperateTime;
        this.reportOperateTime = reportOperateTime;
        this.arriveOperateTime = arriveOperateTime;
        this.subscribeOperateTime = subscribeOperateTime;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.id
     *
     * @return the value of bus_deal.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.real_estate_id
     *
     * @return the value of bus_deal.real_estate_id
     *
     * @mbg.generated
     */
    public Integer getRealEstateId() {
        return realEstateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.real_estate_name
     *
     * @return the value of bus_deal.real_estate_name
     *
     * @mbg.generated
     */
    public String getRealEstateName() {
        return realEstateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.state
     *
     * @return the value of bus_deal.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.customer_id
     *
     * @return the value of bus_deal.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.customer_phone
     *
     * @return the value of bus_deal.customer_phone
     *
     * @mbg.generated
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.customer_name
     *
     * @return the value of bus_deal.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.report_user_id
     *
     * @return the value of bus_deal.report_user_id
     *
     * @mbg.generated
     */
    public Integer getReportUserId() {
        return reportUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.report_user_phone
     *
     * @return the value of bus_deal.report_user_phone
     *
     * @mbg.generated
     */
    public String getReportUserPhone() {
        return reportUserPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.report_company
     *
     * @return the value of bus_deal.report_company
     *
     * @mbg.generated
     */
    public String getReportCompany() {
        return reportCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.appointment_time
     *
     * @return the value of bus_deal.appointment_time
     *
     * @mbg.generated
     */
    public Date getAppointmentTime() {
        return appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.subscribe_time
     *
     * @return the value of bus_deal.subscribe_time
     *
     * @mbg.generated
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.manager_id
     *
     * @return the value of bus_deal.manager_id
     *
     * @mbg.generated
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.manager_phone
     *
     * @return the value of bus_deal.manager_phone
     *
     * @mbg.generated
     */
    public String getManagerPhone() {
        return managerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.arrive_certify_photo_path
     *
     * @return the value of bus_deal.arrive_certify_photo_path
     *
     * @mbg.generated
     */
    public String getArriveCertifyPhotoPath() {
        return arriveCertifyPhotoPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.subscribe_money
     *
     * @return the value of bus_deal.subscribe_money
     *
     * @mbg.generated
     */
    public String getSubscribeMoney() {
        return subscribeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.subscribe_commision
     *
     * @return the value of bus_deal.subscribe_commision
     *
     * @mbg.generated
     */
    public String getSubscribeCommision() {
        return subscribeCommision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.subscribe_photo_pahts
     *
     * @return the value of bus_deal.subscribe_photo_pahts
     *
     * @mbg.generated
     */
    public String getSubscribePhotoPahts() {
        return subscribePhotoPahts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.appointment_operate_time
     *
     * @return the value of bus_deal.appointment_operate_time
     *
     * @mbg.generated
     */
    public Date getAppointmentOperateTime() {
        return appointmentOperateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.report_operate_time
     *
     * @return the value of bus_deal.report_operate_time
     *
     * @mbg.generated
     */
    public Date getReportOperateTime() {
        return reportOperateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.arrive_operate_time
     *
     * @return the value of bus_deal.arrive_operate_time
     *
     * @mbg.generated
     */
    public Date getArriveOperateTime() {
        return arriveOperateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.subscribe_operate_time
     *
     * @return the value of bus_deal.subscribe_operate_time
     *
     * @mbg.generated
     */
    public Date getSubscribeOperateTime() {
        return subscribeOperateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.create_time
     *
     * @return the value of bus_deal.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_deal.update_time
     *
     * @return the value of bus_deal.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setRealEstateId(Integer realEstateId) {
        this.realEstateId = realEstateId;
    }

    public void setRealEstateName(String realEstateName) {
        this.realEstateName = realEstateName;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public void setReportUserId(Integer reportUserId) {
        this.reportUserId = reportUserId;
    }

    public void setReportUserPhone(String reportUserPhone) {
        this.reportUserPhone = reportUserPhone;
    }

    public void setReportCompany(String reportCompany) {
        this.reportCompany = reportCompany;
    }

    public void setAppointmentTime(Date appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    public void setManagerPhone(String managerPhone) {
        this.managerPhone = managerPhone;
    }

    public void setArriveCertifyPhotoPath(String arriveCertifyPhotoPath) {
        this.arriveCertifyPhotoPath = arriveCertifyPhotoPath;
    }

    public void setSubscribeMoney(String subscribeMoney) {
        this.subscribeMoney = subscribeMoney;
    }

    public void setSubscribeCommision(String subscribeCommision) {
        this.subscribeCommision = subscribeCommision;
    }

    public void setSubscribePhotoPahts(String subscribePhotoPahts) {
        this.subscribePhotoPahts = subscribePhotoPahts;
    }

    public void setAppointmentOperateTime(Date appointmentOperateTime) {
        this.appointmentOperateTime = appointmentOperateTime;
    }

    public void setReportOperateTime(Date reportOperateTime) {
        this.reportOperateTime = reportOperateTime;
    }

    public void setArriveOperateTime(Date arriveOperateTime) {
        this.arriveOperateTime = arriveOperateTime;
    }

    public void setSubscribeOperateTime(Date subscribeOperateTime) {
        this.subscribeOperateTime = subscribeOperateTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}