package com.zx.business.model;

import com.zx.business.vo.PageVO;

import java.util.Date;

public class BusNotifyMsg extends PageVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_notify_msg.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_notify_msg.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_notify_msg.deal_id
     *
     * @mbg.generated
     */
    private Integer dealId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_notify_msg.send_user_id
     *
     * @mbg.generated
     */
    private Integer sendUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_notify_msg.receive_user_id
     *
     * @mbg.generated
     */
    private Integer receiveUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_notify_msg.msg_content
     *
     * @mbg.generated
     */
    private String msgContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_notify_msg.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_notify_msg.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    private BusUser receiver;

    public BusUser getReceiver() {
        return receiver;
    }

    public void setReceiver(BusUser receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_notify_msg
     *
     * @mbg.generated
     */
    public BusNotifyMsg(Integer id, Integer type, Integer dealId, Integer sendUserId, Integer receiveUserId, String msgContent, Date createTime, Date updateTime) {
        this.id = id;
        this.type = type;
        this.dealId = dealId;
        this.sendUserId = sendUserId;
        this.receiveUserId = receiveUserId;
        this.msgContent = msgContent;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_notify_msg
     *
     * @mbg.generated
     */
    public BusNotifyMsg() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_notify_msg.id
     *
     * @return the value of bus_notify_msg.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_notify_msg.id
     *
     * @param id the value for bus_notify_msg.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_notify_msg.type
     *
     * @return the value of bus_notify_msg.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_notify_msg.type
     *
     * @param type the value for bus_notify_msg.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_notify_msg.deal_id
     *
     * @return the value of bus_notify_msg.deal_id
     *
     * @mbg.generated
     */
    public Integer getDealId() {
        return dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_notify_msg.deal_id
     *
     * @param dealId the value for bus_notify_msg.deal_id
     *
     * @mbg.generated
     */
    public void setDealId(Integer dealId) {
        this.dealId = dealId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_notify_msg.send_user_id
     *
     * @return the value of bus_notify_msg.send_user_id
     *
     * @mbg.generated
     */
    public Integer getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_notify_msg.send_user_id
     *
     * @param sendUserId the value for bus_notify_msg.send_user_id
     *
     * @mbg.generated
     */
    public void setSendUserId(Integer sendUserId) {
        this.sendUserId = sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_notify_msg.receive_user_id
     *
     * @return the value of bus_notify_msg.receive_user_id
     *
     * @mbg.generated
     */
    public Integer getReceiveUserId() {
        return receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_notify_msg.receive_user_id
     *
     * @param receiveUserId the value for bus_notify_msg.receive_user_id
     *
     * @mbg.generated
     */
    public void setReceiveUserId(Integer receiveUserId) {
        this.receiveUserId = receiveUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_notify_msg.msg_content
     *
     * @return the value of bus_notify_msg.msg_content
     *
     * @mbg.generated
     */
    public String getMsgContent() {
        return msgContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_notify_msg.msg_content
     *
     * @param msgContent the value for bus_notify_msg.msg_content
     *
     * @mbg.generated
     */
    public void setMsgContent(String msgContent) {
        this.msgContent = msgContent == null ? null : msgContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_notify_msg.create_time
     *
     * @return the value of bus_notify_msg.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_notify_msg.create_time
     *
     * @param createTime the value for bus_notify_msg.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_notify_msg.update_time
     *
     * @return the value of bus_notify_msg.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_notify_msg.update_time
     *
     * @param updateTime the value for bus_notify_msg.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}