package com.zx.business.model;

public class BusRealEstate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.summery
     *
     * @mbg.generated
     */
    private String summery;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.commission
     *
     * @mbg.generated
     */
    private String commission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.manager_id
     *
     * @mbg.generated
     */
    private Integer managerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.manager_name
     *
     * @mbg.generated
     */
    private String managerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.is_top_recommend
     *
     * @mbg.generated
     */
    private Boolean isTopRecommend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_real_estate.is_list_recommend
     *
     * @mbg.generated
     */
    private Boolean isListRecommend;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_real_estate
     *
     * @mbg.generated
     */
    public BusRealEstate(Integer id, String summery, String address, String commission, Integer managerId, String managerName, String detail, Boolean isTopRecommend, Boolean isListRecommend) {
        this.id = id;
        this.summery = summery;
        this.address = address;
        this.commission = commission;
        this.managerId = managerId;
        this.managerName = managerName;
        this.detail = detail;
        this.isTopRecommend = isTopRecommend;
        this.isListRecommend = isListRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_real_estate
     *
     * @mbg.generated
     */
    public BusRealEstate() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.id
     *
     * @return the value of bus_real_estate.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.id
     *
     * @param id the value for bus_real_estate.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.summery
     *
     * @return the value of bus_real_estate.summery
     *
     * @mbg.generated
     */
    public String getSummery() {
        return summery;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.summery
     *
     * @param summery the value for bus_real_estate.summery
     *
     * @mbg.generated
     */
    public void setSummery(String summery) {
        this.summery = summery == null ? null : summery.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.address
     *
     * @return the value of bus_real_estate.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.address
     *
     * @param address the value for bus_real_estate.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.commission
     *
     * @return the value of bus_real_estate.commission
     *
     * @mbg.generated
     */
    public String getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.commission
     *
     * @param commission the value for bus_real_estate.commission
     *
     * @mbg.generated
     */
    public void setCommission(String commission) {
        this.commission = commission == null ? null : commission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.manager_id
     *
     * @return the value of bus_real_estate.manager_id
     *
     * @mbg.generated
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.manager_id
     *
     * @param managerId the value for bus_real_estate.manager_id
     *
     * @mbg.generated
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.manager_name
     *
     * @return the value of bus_real_estate.manager_name
     *
     * @mbg.generated
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.manager_name
     *
     * @param managerName the value for bus_real_estate.manager_name
     *
     * @mbg.generated
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName == null ? null : managerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.detail
     *
     * @return the value of bus_real_estate.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.detail
     *
     * @param detail the value for bus_real_estate.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.is_top_recommend
     *
     * @return the value of bus_real_estate.is_top_recommend
     *
     * @mbg.generated
     */
    public Boolean getIsTopRecommend() {
        return isTopRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.is_top_recommend
     *
     * @param isTopRecommend the value for bus_real_estate.is_top_recommend
     *
     * @mbg.generated
     */
    public void setIsTopRecommend(Boolean isTopRecommend) {
        this.isTopRecommend = isTopRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_real_estate.is_list_recommend
     *
     * @return the value of bus_real_estate.is_list_recommend
     *
     * @mbg.generated
     */
    public Boolean getIsListRecommend() {
        return isListRecommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_real_estate.is_list_recommend
     *
     * @param isListRecommend the value for bus_real_estate.is_list_recommend
     *
     * @mbg.generated
     */
    public void setIsListRecommend(Boolean isListRecommend) {
        this.isListRecommend = isListRecommend;
    }
}