package com.zx.business.model;

import java.util.Date;

public class BusRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_role.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_role.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_role.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_role
     *
     * @mbg.generated
     */
    public BusRole(Integer id, String name, Date createTime, String type) {
        this.id = id;
        this.name = name;
        this.createTime = createTime;
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_role.id
     *
     * @return the value of bus_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_role.name
     *
     * @return the value of bus_role.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_role.create_time
     *
     * @return the value of bus_role.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_role.type
     *
     * @return the value of bus_role.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }
}