package com.zx.business.model;

import java.util.Date;

public class BusUser {

    public BusUser() {
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.passwd
     *
     * @mbg.generated
     */
    private String passwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.phone_num
     *
     * @mbg.generated
     */
    private String phoneNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.poll_code
     *
     * @mbg.generated
     */
    private String pollCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.identifying_code
     *
     * @mbg.generated
     */
    private String identifyingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbg.generated
     */
    public BusUser(Integer id, String userName, String passwd, String phoneNum, String pollCode, String identifyingCode, Integer roleId, Date createTime) {
        this.id = id;
        this.userName = userName;
        this.passwd = passwd;
        this.phoneNum = phoneNum;
        this.pollCode = pollCode;
        this.identifyingCode = identifyingCode;
        this.roleId = roleId;
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.id
     *
     * @return the value of bus_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.user_name
     *
     * @return the value of bus_user.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.passwd
     *
     * @return the value of bus_user.passwd
     *
     * @mbg.generated
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.phone_num
     *
     * @return the value of bus_user.phone_num
     *
     * @mbg.generated
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.poll_code
     *
     * @return the value of bus_user.poll_code
     *
     * @mbg.generated
     */
    public String getPollCode() {
        return pollCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.identifying_code
     *
     * @return the value of bus_user.identifying_code
     *
     * @mbg.generated
     */
    public String getIdentifyingCode() {
        return identifyingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.role_id
     *
     * @return the value of bus_user.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.create_time
     *
     * @return the value of bus_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }
}