#Development Environment
spring:
  datasource:
    url: jdbc:mysql://47.106.143.175:3306/real-estate-sales?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  devtools:
    restart:
      enabled: true
  http:
    multipart:
      max-file-size: 50MB  # Single file max size
      max-request-size: 50MB
logging:
  level:
    root: debug

server:
  port: 8080

#Custom configuration
custom:
  system-url: https://inh3rit.top/test
  system-name: 安策营销后台管理系统 - 测试环境
  version: V1.1.0111.1
  directory-path: /home/tony/app2
  is_open_notify: false
