spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    content-type: text/html
  http:
    multipart:
      max-file-size: 50MB  # Single file max size
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm #如果使用字符串表示，用这行设置格式
    time-zone: GMT+8
    serialization: false #使用时间戳，使用数值timestamp表示日期
  datasource:
    url: jdbc:mysql://47.106.143.175:3306/real-estate-sales?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: /mapper/**/*Mapper.xml
  type-aliases-package: com.zx.system.model

logging:
  level:
    root: info

server:
  port: 8080
#Custom configuration
custom:
#  system-url: http://localhost:8080
  system-url: https://inh3rit.top/
  system-name: real-estate-sales-manager
  version: V1.1.0320.1
  page-size: 15
  captcha: 0  # 是否使用登录验证码 0:不使用 1:使用
  file-extension: jpg|png|gif|bmp|jpeg|txt|doc|xls|docx|xlsx|pdf|mp3|mp4|ppt|pptx|rtf|zip|rar|gz|7z|gzip
  directory-path: /home/tony/app
#  directory-path:
  upload-node: upload_files
  wechat.openid.api.url: https://api.weixin.qq.com/sns/jscode2session
  wechat.appid: wx4476c55348a31df8
  wechat.secret: 26754ef3189b3ef8a18d9b5e05d3bb23
  wechat.grant_type: authorization_code
