#Development Environment
spring:
  datasource:
    url: jdbc:mysql://47.106.143.175:3306/real-estate-sales?serverTimezone=Asia/Shanghai&Unicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
    username: root
    password: E9!5521@9
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: true
    mode: LEGACYHTML5
  http:
    multipart:
      max-file-size: 50MB  # Single file max size
      max-request-size: 50MB
logging:
  level:
    root: info

server:
  port: 9000

#Custom configuration
custom:
  system-url: https://inh3rit.top
  system-name: 安策系统
  version: V1.1.0312.1
  directory-path: /home/tony/app
  is_open_notify: true
  upload-node: upload_files
