#Development Environment
spring:
  datasource:
    url: jdbc:mysql://47.106.143.175:3306/real-estate-sales-test?serverTimezone=Asia/Shanghai&Unicode=true&characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
    username: root
    password: E9!5521@9
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  devtools:
    restart:
      enabled: true
  http:
    multipart:
      max-file-size: 50MB  # Single file max size
      max-request-size: 50MB
logging:
  level:
    root: debug

server:
  port: 9876

#Custom configuration
custom:
  system-url: https://ac.eraop.com
  system-name: 安策系统 - 测试环境
  version: V1.1.0111.1
  directory-path: /home/tony/app    #上传文件存储路径，若本地调试可不设置，路径默认为this.getClass().getClassLoader().getResource("").getPath() + "static").substring(1)
  is_open_notify: false
  upload-node: upload_files_test

