#Development Environment
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://47.106.143.175:3306/real-estate-sales?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true


server:
  port: 8080

#Custom configuration
custom:
  captcha: 0
  directory-path: E:/ft
  backup-database-shell-path: E:/ft/backup/backupDB.sh
