package com.zx.business.dao;

import com.zx.business.model.BusAccountManage;

public interface BusAccountManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_account_manage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_account_manage
     *
     * @mbg.generated
     */
    int insert(BusAccountManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_account_manage
     *
     * @mbg.generated
     */
    int insertSelective(BusAccountManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_account_manage
     *
     * @mbg.generated
     */
    BusAccountManage selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_account_manage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusAccountManage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_account_manage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusAccountManage record);

    BusAccountManage getVerifyCode(String phoneNum);
}