package com.zx.business.dao;

import com.zx.business.model.BusAgentCompany;

public interface BusAgentCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_agent_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_agent_company
     *
     * @mbg.generated
     */
    int insert(BusAgentCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_agent_company
     *
     * @mbg.generated
     */
    int insertSelective(BusAgentCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_agent_company
     *
     * @mbg.generated
     */
    BusAgentCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_agent_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusAgentCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_agent_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusAgentCompany record);
}