package com.zx.business.dao;

import com.zx.business.model.BusCustomer;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int insert(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int insertSelective(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    BusCustomer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusCustomer record);

    Long countByModel(BusCustomer busCustomer);

    List<BusCustomer> selectByPage(@Param("start") Integer start, @Param("pageSize") Integer pageSize,
                                   @Param("orderField") String orderField, @Param("orderType") String orderType,
                                   @Param("busCustomer") BusCustomer busCustomer);
}