package com.zx.business.dao;

import com.zx.business.model.BusCustomer;

import java.util.List;

public interface BusCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int insert(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int insertSelective(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    BusCustomer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusCustomer record);

    Long countByModel(BusCustomer busCustomer);

    List<BusCustomer> selectByPage(Integer start, Integer pageSize, String orderField, String orderType, BusCustomer busCustomer);
}