package com.zx.business.dao;

import com.zx.business.model.BusDeal;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusDealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int insert(BusDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int insertSelective(BusDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    BusDeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusDeal record);

    void batchInsert(@Param("busDealList") List<BusDeal> busDealList);

    Long countByModel(BusDeal busDeal);

    List<BusDeal> selectByPage(@Param("start") Integer start, @Param("pageSize") Integer pageSize,
                               @Param("orderField") String orderField, @Param("orderType") String orderType,
                               @Param("busDeal") BusDeal busDeal);
}