package com.zx.business.dao;

import com.zx.business.model.BusDeal;

public interface BusDealMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int insert(BusDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int insertSelective(BusDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    BusDeal selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusDeal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_deal
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusDeal record);
}