package com.zx.business.dao;

import com.zx.business.model.BusRole;

public interface BusRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_role
     *
     * @mbg.generated
     */
    int insert(BusRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_role
     *
     * @mbg.generated
     */
    int insertSelective(BusRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_role
     *
     * @mbg.generated
     */
    BusRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusRole record);
}