package com.zx.business.dao;

import com.zx.base.model.PageCondition;
import com.zx.business.model.BusRealEstate;

import java.util.List;

public interface BusRealEstateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_real_estate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_real_estate
     *
     * @mbg.generated
     */
    int insert(BusRealEstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_real_estate
     *
     * @mbg.generated
     */
    int insertSelective(BusRealEstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_real_estate
     *
     * @mbg.generated
     */
    BusRealEstate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_real_estate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusRealEstate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_real_estate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusRealEstate record);

    List<BusRealEstate> selectByPage(PageCondition condition);

    Long countByModel(BusRealEstate model);
}