package com.zx.business.dao;

import com.zx.business.model.BusUser;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbg.generated
     */
    int insert(BusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbg.generated
     */
    int insertSelective(BusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbg.generated
     */
    BusUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BusUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BusUser record);

    List<BusUser> selectByModel(BusUser busUser);

    long countByModel(BusUser busUser);

    List<BusUser> selectByPage(@Param("start") Integer start, @Param("pageSize") Integer size, @Param("orderField") String orderField,
                               @Param("orderType") String orderType, @Param("busUser") BusUser busUser);

    List<BusUser> getListByRoleType(Integer roleType);
}